import { Suspense } from "react"
import { ShieldCheck } from "lucide-react"
import { getActiveGatePasses } from "@/lib/actions/platinum"
import { GateControlPortal } from "@/components/security/gate-control-portal"

export const metadata = {
    title: "Campus Gate Control | Security",
    description: "Live feed and validation for student Gate Passes."
}

export default async function GateControlPage({ params }: { params: { domain: string } }) {
    // Initial Fetch
    const initialPasses = await getActiveGatePasses() || [];

    return (
        <div className="flex flex-col h-full bg-slate-950 p-6 space-y-8">
            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div className="space-y-1">
                    <div className="flex items-center gap-2">
                        <div className="h-8 w-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center">
                            <ShieldCheck className="h-5 w-5 text-indigo-500" />
                        </div>
                        <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
                            Campus Gate Control
                            <span className="inline-flex items-center rounded-full border border-slate-800 bg-slate-900 px-2 py-0.5 text-xs font-medium text-indigo-400">
                                <span className="mr-1 h-2 w-2 rounded-full animate-pulse bg-indigo-500" />
                                Live Scanner
                            </span>
                        </h1>
                    </div>
                    <p className="text-slate-400 max-w-2xl">
                        Monitor, verify, and authorize active digital gate passes dynamically generated by parents.
                    </p>
                </div>
            </div>

            {/* Main Portal */}
            <div className="rounded-2xl border border-white/10 bg-[#0A0A0B] shadow-2xl overflow-hidden min-h-[600px]">
                <Suspense fallback={<div className="p-8 text-center text-slate-500 animate-pulse font-mono">INITIALIZING SCANNER...</div>}>
                    <GateControlPortal initialPasses={initialPasses} />
                </Suspense>
            </div>
        </div>
    )
}
