-- Mock Seeding for Knowledge Base (Run this in SQL Editor)
-- Note: Real embeddings would need to be generated by the API. 
-- For testing without API keys generating real vectors right now, we can insert dummy data just to verify table structure, but the RAG won't work without real vectors matching the query model.
-- However, I will code the table creation properly.

-- To make RAG fully functional in this "simulation", we would need to run a script to seed this.
-- I will assume for now the table is created.
