import type { Metadata } from "next";
export const dynamic = 'force-dynamic';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";
import { ReactQueryProvider } from "@/components/providers/query-provider";
import { ExecutiveConversionProvider } from "@/components/landing/executive-context"
import { ExecutiveModals } from "@/components/landing/executive-modals"
import { MegaMenu } from "@/components/landing/mega-menu"
import { PhysicalDemoModal } from "@/components/landing/physical-demo-modal"
import { SupportSlideOver } from "@/components/landing/support-slide-over"
import { ExecutiveFocusGlow } from "@/components/landing/executive-focus-glow"

import { UserPreferencesProvider } from "@/components/providers/user-preferences-provider";
import { OfflineSyncProvider } from "@/components/providers/offline-sync-provider";
import { RealtimeNotifications } from "@/components/layout/realtime-notifications";
import { TrayTicker } from "@/components/dashboard/tray-ticker";
import { VoiceAssistant } from "@/components/dashboard/voice-assistant";
import { BiometricGuard } from "@/components/auth/biometric-guard";
import { OfflineVaultProvider } from "@/components/providers/offline-vault-provider";
import { KioskProvider } from "@/components/providers/kiosk-provider";
import { LoadingBar } from "@/components/layout/loading-bar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                try {
                  // 1. Theme Detection
                  let isDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  const store = localStorage.getItem('preferences-storage');
                  if (store) {
                    const parsed = JSON.parse(store);
                    const theme = parsed?.state?.theme;
                    if (theme === 'dark') isDark = true;
                    if (theme === 'light') isDark = false;
                  }
                  if (isDark) document.documentElement.classList.add('dark');

                  // 2. Tauri Environment Detection (Flash Protection + Smart Bypass)
                  if (window.__TAURI_INTERNALS__ || window.__TAURI__) {
                    document.documentElement.classList.add('tauri-desktop');
                    
                    // Smart Bypass: If at root, redirect to the last visited school dashboard
                    if (window.location.pathname === '/' || window.location.pathname === '/index.html') {
                      document.write('<style>body { visibility: hidden !important; background: black !important; }</style>');
                      const lastSlug = localStorage.getItem('eduflow-last-slug') || 'school1';
                      window.location.replace('/' + lastSlug + '/dashboard');
                    }
                  }
                } catch (e) {}
              `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <LoadingBar />
          <UserPreferencesProvider>
            <OfflineSyncProvider>
              <RealtimeNotifications />
              <TrayTicker />
              <VoiceAssistant />
              <BiometricGuard>
                <OfflineVaultProvider>
                  <KioskProvider>
                    {children}
                  </KioskProvider>
                </OfflineVaultProvider>
              </BiometricGuard>
            </OfflineSyncProvider>
          </UserPreferencesProvider>
          <Toaster theme="dark" richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
