import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";
import { ReactQueryProvider } from "@/components/providers/query-provider";
import { ExecutiveConversionProvider } from "@/components/landing/executive-context"
import { ExecutiveModals } from "@/components/landing/executive-modals"
import { MegaMenu } from "@/components/landing/mega-menu"
import { PhysicalDemoModal } from "@/components/landing/physical-demo-modal"
import { SupportSlideOver } from "@/components/landing/support-slide-over"
import { ExecutiveFocusGlow } from "@/components/landing/executive-focus-glow"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <ExecutiveConversionProvider>
            {children}
            <ExecutiveModals />
            <MegaMenu />
            <PhysicalDemoModal />
            <SupportSlideOver />
            <ExecutiveFocusGlow />
          </ExecutiveConversionProvider>
          <Toaster theme="dark" richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
