import { CalendarDays } from "lucide-react"

export default function StudentTimetablePage() {
    return (
        <div className="p-6 md:p-8 max-w-7xl mx-auto min-h-screen bg-slate-950 flex flex-col items-center justify-center text-center space-y-6">
            <div className="h-24 w-24 bg-slate-900 rounded-full flex items-center justify-center border border-white/10">
                <CalendarDays className="h-10 w-10 text-[var(--school-accent)]" />
            </div>

            <div>
                <h1 className="text-3xl font-bold text-white mb-2">Class Timetable</h1>
                <p className="text-slate-400 max-w-md mx-auto">
                    Your personalized class schedule is being generated by the Academic Office.
                    Please check back later or contact your class teacher.
                </p>
            </div>

            <div className="p-4 bg-[var(--school-accent)]/10 text-[var(--school-accent)] rounded-lg text-sm border border-[var(--school-accent)]/20">
                Status: AWAITING_PUBLICATION
            </div>
        </div>
    )
}
